---
title: "Homework 3"
author: Jennifer Mizhquiri
output: github_document
---


```{r, echo = FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

Loaded instacart data
```{r, echo = FALSE}

library(p8105.datasets)
data("instacart")
```

## Problem 2

_Office Hours_ 
* how can i make leverage || , OR 
* how to load a promise object and view it...

```{r}
accel_df = 
  read_csv("./data/accel_data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    weekend = if_else(day == "Saturday", 1, if_else(day == "Sunday", 1, 0))
  ) %>% 
  select(
    week, day_id, weekend, day, everything()
  ) %>%
  pivot_longer(
    activity_1:activity_1440,
    names_to = "min_24h",
    values_to = "activity_count",
    names_prefix = "activity_") %>% 
  mutate(
    min_24h = as.numeric(min_24h)
  )

```


